#!/usr/bin/php
<?php 

require 'vendor/autoload.php';

$client = new Goutte\Client();

/*

# CRAWLER for scrapping TV Shows

const STREAM_URL = 'https://french-stream.re/serie/15609-person-of-interest-saison-2-streaming-complet-vf-vostfr.html';

$crawler = $client->request('GET', STREAM_URL);
$hrefs = $crawler->filter('div.elink .fstab')->each(function ($node) {
    return $node->attr('href');
});
$titles = $crawler->filter('div.elink .fstab')->each(function ($node) {
    return $node->text();
});

$db = [
    'person-of-interest-season' => array_combine($titles, $hrefs),
];

*/

/*

# CRAWLER for FOOT Stream

const BASE_URL = 'https://www.streamonsport4.click';
const STREAM_URL = 'https://www.streamonsport4.click/3200-regarder-cremonese-as-rome-en-streaming-serie-a.html';

$crawler = $client->request('GET', STREAM_URL);

$streamUrls = $crawler->filter('div#chanel_links a')->each(function ($node) {
    return $node->attr('onclick');
});

$identifier = [];
foreach ($streamUrls as $url) 
{
    $explodeArr = explode("'", $url);
    foreach ($explodeArr as $array) 
    {
        if (preg_match('#/#', $array))
        {
            if (preg_match('#https#', $array))
            {
                $uriFormat = explode("id=", $array);

                foreach ($uriFormat as $uri)
                {
                    if (str_contains($uri, 'https')) {
                        $identifier[] = $uri;
                    }
                }
            } else {

                $identifier[] = BASE_URL.$array;
            }
        }
    }
}
*/

$db = [
    'movies' => [
        [
            'title' => 'Shark Tank - Season 3 - E3',
            'browser_uuid' => 'https://bmovies.vip/film/shark-tank-season-3-14992/watching.html?ep=14992_3_1',
        ],
        [
            'title' => 'Shark Tank - Season 3 - E4',
            'browser_uuid' => 'https://bmovies.vip/film/shark-tank-season-3-14992/watching.html?ep=14992_4_1',
        ],
    ]
];

$edb = json_encode($db);
file_put_contents('db.json', $edb);
