#!/usr/bin/php
<?php 

require 'vendor/autoload.php';

$client = new Goutte\Client();

const STREAM_URL = 'https://french-stream.re/serie/15608-person-of-interest-saison-1-streaming-complet-vf-vostfr.html';

$crawler = $client->request('GET', STREAM_URL);
$hrefs = $crawler->filter('div.elink .fstab')->each(function ($node) {
    return $node->attr('href');
});
$titles = $crawler->filter('div.elink .fstab')->each(function ($node) {
    return $node->text();
});
$db = [
    'person-of-interest-season-1' => array_combine($titles, $hrefs),
];
$edb = json_encode($db);

file_put_contents('db.json', $edb);
